[package]
name = "tarpc-server"
version = "0.2.0"
edition = "2024"

[dependencies]
rpc-model = { path = "../rpc-model/" }

tarpc = { version = "0.37.0", features = ["full"] }
tokio = { version = "1.48.0", features = ["full"] }
anyhow = "1.0.100"
futures = "0.3.31"
